
package com.parameta.controller;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmpleadoControllerImplService", targetNamespace = "http://controller.parameta.com/", wsdlLocation = "http://localhost:1234/WS/Empleado?WSDL")
public class EmpleadoControllerImplService
    extends Service
{

    private final static URL EMPLEADOCONTROLLERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLEADOCONTROLLERIMPLSERVICE_EXCEPTION;
    private final static QName EMPLEADOCONTROLLERIMPLSERVICE_QNAME = new QName("http://controller.parameta.com/", "EmpleadoControllerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/WS/Empleado?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLEADOCONTROLLERIMPLSERVICE_WSDL_LOCATION = url;
        EMPLEADOCONTROLLERIMPLSERVICE_EXCEPTION = e;
    }

    public EmpleadoControllerImplService() {
        super(__getWsdlLocation(), EMPLEADOCONTROLLERIMPLSERVICE_QNAME);
    }

    public EmpleadoControllerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLEADOCONTROLLERIMPLSERVICE_QNAME, features);
    }

    public EmpleadoControllerImplService(URL wsdlLocation) {
        super(wsdlLocation, EMPLEADOCONTROLLERIMPLSERVICE_QNAME);
    }

    public EmpleadoControllerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLEADOCONTROLLERIMPLSERVICE_QNAME, features);
    }

    public EmpleadoControllerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpleadoControllerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmpleadoController
     */
    @WebEndpoint(name = "EmpleadoControllerImplPort")
    public EmpleadoController getEmpleadoControllerImplPort() {
        return super.getPort(new QName("http://controller.parameta.com/", "EmpleadoControllerImplPort"), EmpleadoController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpleadoController
     */
    @WebEndpoint(name = "EmpleadoControllerImplPort")
    public EmpleadoController getEmpleadoControllerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.parameta.com/", "EmpleadoControllerImplPort"), EmpleadoController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLEADOCONTROLLERIMPLSERVICE_EXCEPTION!= null) {
            throw EMPLEADOCONTROLLERIMPLSERVICE_EXCEPTION;
        }
        return EMPLEADOCONTROLLERIMPLSERVICE_WSDL_LOCATION;
    }

}
