
package com.parameta.controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpleadoController", targetNamespace = "http://controller.parameta.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpleadoController {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.parameta.controller.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "almacenarEmpleado", targetNamespace = "http://controller.parameta.com/", className = "com.parameta.controller.AlmacenarEmpleado")
    @ResponseWrapper(localName = "almacenarEmpleadoResponse", targetNamespace = "http://controller.parameta.com/", className = "com.parameta.controller.AlmacenarEmpleadoResponse")
    @Action(input = "http://controller.parameta.com/EmpleadoController/almacenarEmpleadoRequest", output = "http://controller.parameta.com/EmpleadoController/almacenarEmpleadoResponse")
    public Response almacenarEmpleado(
        @WebParam(name = "arg0", targetNamespace = "")
        Empleado arg0);

}
